// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcbkvrapjvdfpjuljqtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYmt2cmFwanZkZnBqdWxqcXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDgwOTYsImV4cCI6MjA2MDAyNDA5Nn0.2Vkb7Lt1KeAZEYU796vmSOxH7EQd0fKe9KrRJ4GEFts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);